default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123
  host: localhost

development:
  <<: *default
  database: grepfull_development

production:
  <<: *default
  database: grepfull_production

test:
  <<: *default
  database: grepfull_test
